import { withApp } from './ui-harness.mjs';
const fire = (app, el) => el.dispatchEvent(new app.window.MouseEvent('click', { bubbles: true, cancelable: true }));
const modal = (app) => [...app.document.querySelectorAll('div')].filter(d => d.style.position === 'fixed' && d.style.zIndex === '80')[0];
const B = (root, label, nth=0) => [...root.querySelectorAll('button')].filter(b => (b.textContent||'').trim() === label)[nth];
const openOrder = async (app, id) => {
  const card = [...app.document.querySelectorAll('div')].find(d => (d.textContent||'').startsWith('#'+id));
  fire(app, card); await app.settle(); return modal(app);
};
const itemsText = (M) => M.textContent.replace(/\s+/g,' ').match(/Items · editing.*?Close product picker/)?.[0];
const newTotal = (M) => M.textContent.replace(/\s+/g,' ').match(/New total(\$[\d.,]+)/)?.[1];

await withApp('pos', async (app) => {
  await app.mount('OrdersScreen');
  let M = await openOrder(app, 'ORD-00224');
  fire(app, B(M,'Edit order')); await app.settle(); M = modal(app);
  fire(app, B(M,'Add item')); await app.settle(); M = modal(app);
  console.log('items before Add:', itemsText(M));
  console.log('--- click first Add ---');
  const add = B(M,'Add',0);
  console.log('Add disabled?', add.disabled);
  fire(app, add); await app.settle(); M = modal(app);
  console.log('items after Add:', itemsText(M));
  console.log('newTotal:', newTotal(M));
  console.log('--- click an "In order (4)" button ---');
  const io = B(M,'In order (4)',0);
  console.log('exists:', !!io, 'disabled:', io && io.disabled);
  const before = itemsText(M);
  if (io) fire(app, io); await app.settle(); M = modal(app);
  console.log('changed:', before !== itemsText(M));
  console.log('--- Promo Apply ---');
  const inputs = [...M.querySelectorAll('input')];
  console.log('inputs placeholders:', inputs.map(i=>i.getAttribute('placeholder')));
  const promoIn = inputs.find(i => (i.getAttribute('placeholder')||'').includes('SUMMER15'));
  const setter = Object.getOwnPropertyDescriptor(app.window.HTMLInputElement.prototype,'value').set;
  const applyBtn0 = B(M,'Apply');
  console.log('Apply disabled with empty code:', applyBtn0.disabled);
  setter.call(promoIn, 'BOGO5'); promoIn.dispatchEvent(new app.window.Event('input',{bubbles:true}));
  await app.settle(); M = modal(app);
  console.log('Apply disabled with code:', B(M,'Apply').disabled);
  fire(app, B(M,'Apply')); await app.settle(); M = modal(app);
  const t = M.textContent.replace(/\s+/g,' ');
  console.log('promo chip:', /Promo · BOGO5/.test(t), 'newTotal:', newTotal(M));
  console.log('--- bad code ---');
  const pi2 = [...M.querySelectorAll('input')].find(i => (i.getAttribute('placeholder')||'').includes('SUMMER15'));
  setter.call(pi2, 'NOPECODE'); pi2.dispatchEvent(new app.window.Event('input',{bubbles:true}));
  await app.settle(); M = modal(app);
  fire(app, B(M,'Apply')); await app.settle(); M = modal(app);
  console.log('error shown:', /No promo with that code/.test(M.textContent));
  console.log('errors:', app.errors);
});
