import { bootDriver, labels, clickSel, state, onDuty, scanAll, btn, clickBtn } from './test/_drive.mjs';
const app = await bootDriver();
await onDuty(app);
clickSel(app, '[data-tour="stop"]', 0); await app.settle();
console.log('scans:', await scanAll(app)); await app.settle();
console.log('close out click:', clickBtn(app, /^Close out/)); await app.settle();
console.log('STACK', state(app).stack.map(s=>s.name));
console.log('BTN', JSON.stringify(labels(app).slice(15)));
console.log('TEXT', app.text().replace(/^.*?Settings/,'').slice(0,900));
console.log('ERR', app.errors);
app.close();
