import { bootDriver, labels, clickSel, state, onDuty, scanAll, btn, clickBtn } from './test/_drive.mjs';
const app = await bootDriver();
await onDuty(app);
clickSel(app, '[data-tour="stop"]', 0); await app.settle();
await scanAll(app);
clickBtn(app, /^Close out/); await app.settle();
clickBtn(app, /^Scan customer ID/); await app.settle();
[...app.document.querySelectorAll('button')].find(b=>!(b.textContent||'').trim() && /width: 70px/.test(b.getAttribute('style')||'')).dispatchEvent(new app.window.MouseEvent('click',{bubbles:true}));
await app.settle();
clickBtn(app, /Save to profile/); await app.settle();
console.log('Card click:', clickBtn(app, /^EXPECTEDCard$/)); await app.settle();
console.log('payment overlay?', /Take payment/.test(app.text()));
console.log('BTN', JSON.stringify(labels(app).slice(15)));
console.log('charge click:', clickBtn(app, /^Charge card/)); await app.settle();
await new Promise(r=>setTimeout(r,1600));
console.log('BTN2', JSON.stringify(labels(app).slice(15)));
console.log('approve:', clickBtn(app, /^Approve$/));
await new Promise(r=>setTimeout(r,3000));
console.log('after approve text has Delivered?', /Delivered to/.test(app.text()));
console.log('BTN3', JSON.stringify(labels(app).slice(15)));
console.log('completed', app.window.M.s.completed.map(c=>({t:c.taskId,total:c.total,collected:c.collected,method:c.method})));
console.log('ERR', app.errors);
app.close();
