import { bootDriver, labels, clickSel, state, onDuty, scanAll, btn, clickBtn } from './test/_drive.mjs';
const app = await bootDriver();
await onDuty(app);
clickSel(app, '[data-tour="stop"]', 0); await app.settle();
await scanAll(app);
clickBtn(app, /^Close out/); await app.settle();
clickBtn(app, /^Scan customer ID/); await app.settle();
[...app.document.querySelectorAll('button')].find(b=>!(b.textContent||'').trim() && /width: 70px/.test(b.getAttribute('style')||'')).dispatchEvent(new app.window.MouseEvent('click',{bubbles:true}));
await app.settle();
clickBtn(app, /Save to profile/); await app.settle();
clickBtn(app, /^EXPECTEDCard$/); await app.settle();
console.log('charge:', clickBtn(app, /^Charge card/)); await app.settle();
await new Promise(r=>setTimeout(r,1600));
console.log('terminal text:', /Follow the prompts/.test(app.text()));
console.log('approve:', clickBtn(app, /^Approve$/));
await new Promise(r=>setTimeout(r,3200));
console.log('Delivered?', /Delivered to/.test(app.text()));
console.log('completed', app.window.M.s.completed.map(c=>({t:c.taskId,total:c.total,collected:c.collected,method:c.method,fee:c.fee})));
console.log('BTN', JSON.stringify(labels(app).slice(15)));
console.log('next stop:', clickBtn(app, /Next stop/)); await app.settle();
console.log('STATE', state(app).stack.map(s=>s.name), state(app).tab);
console.log('home shows completed?', /Completed1/.test(app.text().replace(/\s+/g,'')));
console.log('ERR', app.errors);
app.close();
